### ISSUE TITLE
Playwright Rules Generator (PRG)

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#18]
> [!NOTE]
> Within the scope of this issue, `PRG` stands for `Playwright Rules Generator`

AS AN Architect
I WANT my Playwright tests to be created based on easy-to-understand YAML-based DSL files
SO THAT replicating existing tests to other resource would require as few developer's assistance as possible

### Acceptance Criteria

- [ ] The result of PRG is a fully [Playwright](https://playwright.dev)-compatible test

#### DSL

- [ ] Define the structure of PRG DSLs in co-operation with Bürokratt architect
- [ ] DSL's are based on `YAML` files
- [ ] Every test file can contain one to many different tests
- [ ] Combination of Playwright's functionalities (such as using [_and_](https://playwright.dev/docs/api/class-locator#locator-and), [_not_](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-not), etc.) must be supported

#### Scope

- [ ] Up to 20 [Locators](https://playwright.dev/docs/api/class-locator)
- [ ] Up to 20 [LocatorAssertions](https://playwright.dev/docs/api/class-locatorassertions)
