### ISSUE TITLE
Set up GitHub Actions to run Playwright tests

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#19]
AS AN Architect
I WANT Playwright tests to be run automatically whenever there is a pull request to given GitHub repository
SO THAT pull requests with poor code quality would not end up in destination branch

### Acceptance Criteria

- [ ] Based on [Playwright's CI GitHub Actions](https://playwright.dev/docs/ci-intro)
- [ ] Upon any pull request, Playwright tests are run
- [ ] If any of the tests fail, pull request is automatically rejected
