### ISSUE TITLE
Publish Playwright test reports

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#20]
AS A Developer
I WANT Playwright test results to be immediately published after running the tests
SO THAT I would have an overview of what needs to be fixed

AS A Product Owner / Dev Lead
I WANT to have an overview of historical Playwright test results
SO THAT I would have a better overview of the quality of our developments

### Acceptance Criteria

- [ ] All test results are published to a defined destination right after they have been created
- [ ] Test reports are automatically generated and contain the time of their generation and link to GitHub commit
- [ ] Test reports are grouped by date
- [ ] The location of test results is configurable via a settings file
- [ ] The number of test results to be shown is configurable via a settings file
