### ISSUE TITLE
Create Playwright tests for Bürokratt's GUI

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#21]
AS A Product Owner
I WANT Bürokratt's GUI to be covered with automated tests
SO THAT I could be confident in their quality

### Acceptance Criteria

- [ ] All tests must be based on DSLs created by **Playwright Rules Generator (PRG)**
- [ ] Automated tests must cover all existing functionality of each GUI

#### Scope

- [ ] [Chat Widget](https://github.com/buerokratt/Chat-Widget)
- [ ] [Backoffice](https://github.com/buerokratt/Buerokratt-Chatbot)
- [ ] [Training Module](https://github.com/buerokratt/Training-Module)
- [ ] [Analytics Module](https://github.com/buerokratt/Analytics-Module)
- [ ] [Service Module](https://github.com/buerokratt/Service-Module)
