### ISSUE TITLE
Remove bugs, vulnerabilities, etc.

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#5]
AS InfoSec
I WANT all detected security-related issues to be removed from the source code
SO THAT there wouldn't be any known vulnerabilities

### Acceptance Criteria

- [ ] [Snyk](https://snyk.io) reports 0 vulnerabilities and bugs, unless reported as `unfixable`
- [ ] [Sonarcloud](https://sonarcloud.io/) reports 0 vulnerabilities and bugs, unless reported as `unfixable`

#### How to

- [ ] Run tests based on your personal GitHub fork on your Snyk account
- [ ] Run tests based on your personal GitHub fork on your Sonarcloud account
- [ ] Commit your fixes not less than once a day to applicable Bürokratt's `dev` branches

#### Priorities

- [ ] Remove `Critical` and `High` impact issues first and then move to other Components / Modules
- [ ] If no `Critical` and `High` impact issues exist on any Components / Modules, move on to `Medium`
- [ ] If no `Medium` impact issues exist on any Components / Modules, move on to `Low`

#### Scope

> See https://github.com/buerokratt/Test-Driven-Development/issues/2 for additional information

##### Deployment

- [ ] buerokratt/NoOps#154

##### Components

- [ ] buerokratt/Ruuter#286
- [ ] buerokratt/DataMapper#39
- [ ] buerokratt/Resql#55
- [ ] buerokratt/TIM#22
- [ ] buerokratt/S3-Ferry#5
- [ ] buerokratt/CronManager#20

##### Modules

- [x] buerokratt/Chat-Widget#114
- [x] buerokratt/Buerokratt-Chatbot#535
- [x] buerokratt/Analytics-Module#197
- [x] buerokratt/Service-Module#256
- [x] buerokratt/Training-Module#455
